//bcrypt - package to encrypt data


const data = {

  // users: [
  //   {
  //     name: "John",
  //     email: "admin@example.com",
  //     password: bcrypt.hashSync("123456"),
  //     isAdmin: true
  //   },
  //   {
  //     name: "Jane",
  //     email: "jane@example.com",
  //     password: bcrypt.hashSync("123456"),
  //     isAdmin: false
  //   }
  // ],

  products: [
    {
      id: 1,
      name: "Wall Plant Deco",
      image: "/assets/Product1.jpeg",
      description: "Beautiful homely wall plant",
      price: 20,
      category: "plants",
      rating: 5,
      countInStock: 10,
    },
    {
      id: 2,
      name: "Shelf",
      image: "/assets/Product2.jpeg",
      description: "Beautiful homely shelf for kitchen or bedroom",
      price: 13.5,
      category: "shelves",
      rating: 4,
      countInStock: 10,
    },
    {
      id: 3,
      image: "/assets/Product3.jpeg",
      name: "Coffee Table",
      description: "Beautiful homely coffee table",
      price: 85.0,
      category: "tables",
      rating: 3,
      countInStock: 10,
    },
    {
      id: 4,
      image: "/assets/Product4.jpeg",
      name: "Living Set",
      description: "Beautiful homely living set",
      price: 625,
      category: "living",
      rating: 4,
      countInStock: 10,
    },
    {
      id: 5,
      image: "/assets/Product5.jpeg",
      name: "Kitchen Shelf",
      description: "Beautiful homely kitchen shelf",
      price: 35,
      category: "shelves",
      rating: 4,
      countInStock: 10,
    },
    {
      id: 6,
      name: "Sofa with Drawers",
      image: "/assets/Product6.jpeg",
      description: "Beautiful homely sofa with drawers",
      price: 625,
      category: "living",
      rating: 5,
      countInStock: 10,
    },
    {
      id: 7,
      image: "/assets/Product7.webp",
      name: "Coffee table with wheels",
      description: "Beautiful homely coffee table with wheels",
      price: 625,
      category: "tables",
      rating: 5,
      countInStock: 10,
    },
    {
      id: 8,
      image: "/assets/Product8.jpeg",
      name: "Bed Set",
      description: "Beautiful homely bed set",
      price: 400,
      category: "bedroom",
      rating: 4,
      countInStock: 10,
    },
    {
      id: 9,
      image: "/assets/Product9.jpeg",
      name: "Nordic Night table",
      description: "Beautiful homely nordic night table",
      price: 30,
      category: "tables",
      rating: 3,
      countInStock: 10,
    },
    {
      id: 10,
      image: "/assets/Product10.jpeg",
      name: "Classic Night table",
      description: "Beautiful homely classic night table",
      price: 25,  
      category: "tables",
      rating: 4,
      countInStock: 10,
    },
    {
      id: 11,
      image: "/assets/Product11.jpeg",
      name: "Kitchen Shelf 1",
      description: "Beautiful homely kitchen shelf",
      price: 20,
      category: "shelves",
      rating: 3,
      countInStock: 10,
    },
    {
      id: 12,
      image: "/assets/Product12.jpeg",
      name: "Kitchen Shelf 2",
      description: "Beautiful homely kitchen shelf",
      price: 15,
      category: "shelves",
      rating: 4,
      countInStock: 10,
    },
  ],
};

export default data;